INSERT INTO tb_categoria(tipo, descricao) VALUES ('Luta','Jogo de player vs player');
INSERT INTO tb_categoria(tipo, descricao) VALUES ('Aventura','Jogo de historia');

INSERT INTO tb_produto(name,preco,descricao,img_url,platafor,categoria_id) VALUES ('Mortal Kombat 1',240.69,'Descubra um Universo renascido de Mortal Kombat criado pelo Deus do Fogo Liu Kang. Mortal Kombat 1 inaugura uma nova era da franquia icônica com um novo sistema de luta, modos de jogo e fatalities!','https://assets.nuuvem.com/image/upload/t_banner_big/v1/products/646686699af000001520ca83/banners/o4m5kyahvxzhp2ak5v3b.jpg',' PlayStation, Xbox Series X|S, Nintendo Switch e PC (Epic Games e Steam)',1);
INSERT INTO tb_produto(name,preco,descricao,img_url,platafor,categoria_id) VALUES ('Batman Arkham Collection',27.99,'Batman: Arkham City baseia-se na intensa e atmosférica fundação de Batman: Arkham Asylum, fazendo com que os jogadores voem pela extensa Arkham City - cinco vezes maior do que o mundo do jogo em Batman.','https://assets.nuuvem.com/image/upload/t_screenshot_full/v1/products/61437f66a3f8b1386fb570e3/screenshots/ujz6icxc1dgm1nei21he.jpg',' PlayStation, Xbox Series X|S, Nintendo Switch e PC (Epic Games e Steam)',2);
INSERT INTO tb_produto(name,preco,descricao,img_url,platafor,categoria_id) VALUES ('The Legend of Zelda™️️️️️️️: Tears of The Kingdom',357.69,'Explore as vastas terras e os céus de Hyrule Uma aventura épica pela terra e pelos céus de Hyrule lhe aguarda em The Legend of Zelda™: Tears of the Kingdom para o console Nintendo Switch. Você é quem cria essa aventura em um mundo alimentado por sua imaginação.','https://assets.nuuvem.com/image/upload/t_screenshot_full/v1/products/6436f817b6a147001a7ea5c8/screenshots/h6kmpxpzzucbs0bhzo0a.jpg','Nintendo Switch',2);
INSERT INTO tb_produto(name,preco,descricao,img_url,platafor,categoria_id) VALUES ('Middle-earth: Shadow of War',11.50,'Entre por trás das linhas inimigas para forjar seu exército, conquistar Fortalezas e dominar Mordor a partir de dentro. Experimente como o premiado Sistema de Rival cria histórias pessoais únicas a cada inimigo e seguidor, e enfrente o poder total do Senhor do Escuro, Sauron, e seus Espectros do Anel nesta nova história épica da Terra-média. ','https://assets.nuuvem.com/image/upload/t_banner_big/v1/products/58c19baa2162480d8d0001f3/banners/zsq9rigorpcrxlejbiw0.jpg','PlayStation, Xbox Series X|S, Nintendo Switch e PC (Epic Games e Steam)',1);
INSERT INTO tb_produto(name,preco,descricao,img_url,platafor,categoria_id) VALUES ('Street Fighter 6',219.11,'Aí vem o novo desafiante da Capcom! Street Fighter™ 6 será lançado no mundo inteiro em 2 de junho de 2023 e representa a próxima evolução da série.','https://assets.nuuvem.com/image/upload/t_banner_big/v1/products/63976a036f34382ac1ef29d6/banners/v41y7co3jutkkdcm7uab.jpg',' PlayStation, Xbox Series X|S, Nintendo Switch e PC (Epic Games e Steam)',1);

